### PR TITLE
[Addon Upgrade] Jaeger

### PR DESCRIPTION
**Pull request by balchua**
Upgrade Jaeger Operator to `v1.36.0`.

**Warning** Jaeger Operator from v1.31, now requires cert-manager to be installed.
This PR utilizes the cert-manager core addon.

*Also verify you have:*
* [X] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [X] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for this PR @balchua. I am not able to run the tests on a clean system, the operator pod is stuck to a ContainerCreating state with the following in its events log:
```
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  2m29s (x2 over 6m59s)  kubelet  Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[cert kube-api-access-sf25d]: timed out waiting for the condition
  Warning  FailedMount  48s (x12 over 9m2s)    kubelet  MountVolume.SetUp failed for volume "cert" : secret "jaeger-operator-service-cert" not found
  Warning  FailedMount  12s (x2 over 4m43s)    kubelet  Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[kube-api-access-sf25d cert]: timed out waiting for the condition
```

Do we need to create the mentioned secret in our enable script?

**Comment by balchua** [comment]
No extra thing to create.  Can i check with you if you have cert-manager addon?

**Comment by ktsakalozos** [comment]
Here is how the cert manager gets enabled as part of the jaeger addon:
```
Enabled cert-manager                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                           
===========================                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                           
Cert-manager is installed. As a next step, try creating a ClusterIssuer                                                                                                                                                                                                                                                                                                                    
for Let's Encrypt by creating the following resource:                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                           
$ microk8s kubectl apply -f - <<EOF                                                                                                                                                                                                                                                                                                                                                        
---                                                                                                                                                                                                                                                                                                                                                                                        
apiVersion: cert-manager.io/v1                                                                                                                                                                                                                                                                                                                                                             
kind: ClusterIssuer                                                                                                                                                                                                                                                                                                                                                                        
metadata:                                                                                                                                                                                                                                                                                                                                                                                  
  name: letsencrypt                                                                                                                                                                                                                                                                                                                                                                        
spec:                                                                                                                                                                                                                                                                                                                                                                                      
  acme:                                                                                                                                                                                                                                                                                                                                                                                    
    # You must replace this email address with your own.                                                                                                                                                                                                                                                                                                                                   
    # Let's Encrypt will use this to contact you about expiring                                                                                                                                                                                                                                                                                                                            
    # certificates, and issues related to your account.                                                                                                                                                                                                                                                                                                                                    
    email: me@example.com                                                                                                                                                                                                                                                                                                                                                                  
    server: https://acme-v02.api.letsencrypt.org/directory                                                                                                                                                                                                                                                                                                                                 
    privateKeySecretRef:                                                                                                                                                                                                                                                                                                                                                                   
      # Secret resource that will be used to store the account's private key.                                                                                                                
      name: letsencrypt-account-key         
    # Add a single challenge solver, HTTP01 using nginx            
    solvers:                                                                                                                           
    - http01:                                                                                                                          
        ingress:                                                   
          class: public            
EOF                                                                                                                                                                                                                                                                            
                                                                                                                                       
Then, you can create an ingress to expose 'my-service:80' on 'https://my-service.example.com' with:                                    
                                                                                                                                       
$ microk8s enable ingress                                                                                                              
$ microk8s kubectl create ingress my-ingress     --annotation cert-manager.io/cluster-issuer=letsencrypt     --rule 'my-service.example.com/*=my-service:80,tls=my-service-tls'                                                                                                                                                                                                            
                                                                                                                                       
customresourcedefinition.apiextensions.k8s.io/jaegers.jaegertracing.io created                                                                                                               
serviceaccount/jaeger-operator created                         
role.rbac.authorization.k8s.io/leader-election-role created                                                                            
role.rbac.authorization.k8s.io/prometheus created       
clusterrole.rbac.authorization.k8s.io/jaeger-operator-metrics-reader created                                                           
clusterrole.rbac.authorization.k8s.io/manager-role created                                                                             
clusterrole.rbac.authorization.k8s.io/proxy-role created                                                                               
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created                                                                                                                    
rolebinding.rbac.authorization.k8s.io/prometheus created                                                                               
clusterrolebinding.rbac.authorization.k8s.io/jaeger-operator-proxy-rolebinding created                          
clusterrolebinding.rbac.authorization.k8s.io/manager-rolebinding created                                            
service/jaeger-operator-metrics created                                                                                                                                                                                                                                        
service/jaeger-operator-webhook-service created                                                                                        
deployment.apps/jaeger-operator created                                                                                                                                                                                                                                        
mutatingwebhookconfiguration.admissionregistration.k8s.io/jaeger-operator-mutating-webhook-configuration created                       
validatingwebhookconfiguration.admissionregistration.k8s.io/jaeger-operator-validating-webhook-configuration created                   
Error from server (InternalError): error when creating "/var/snap/microk8s/common/addons/j/addons/jaeger/operator.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.152.183.27:443: connect: connection refused
Error from server (InternalError): error when creating "/var/snap/microk8s/common/addons/j/addons/jaeger/operator.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.152.183.27:443: connect: connection refused
```

**Comment by balchua** [comment]
I think i may have an idea what is going on.  The cert-manager pod is probably not ready yet when the operator is installed.
Let me try adding a wait for cert-manager to be ready before proceeding with the installing the operator.
I will put this one to wip while i settle this one.
Apologies for the inconvenience.

**Comment by balchua** [comment]
Found out that cert-manager takes quite sometime to really get ready.  In fact their installation steps spells this out.
I think we should include that test in the `cert-manager` addon.  wdyt?
For now, i applied the cert-manager test in the jaeger addon.

**Comment by balchua** [comment]
I created an issue in the core addons. https://github.com/canonical/microk8s-core-addons/issues/82 in case this is a good addition to the UX.

**Review by ktsakalozos — APPROVED** [review]
LGTM +1 thank you @balchua

**Comment by balchua** [comment]
Thanks!! 🙏

**Pull request merged**
