### PR TITLE
get current istio release v1.14.4

### PR DESCRIPTION
**Pull request by Azuna1**
v1.10.3 is an 2 years old release with multiple vulnerabilities v1.14.4 is current

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Hi @Azuna1 thank you for this PR
Could you please sign the CLA agreement with the email used in the git commits? Here the error the CLA check shows:
```
Checking the following users on Launchpad:
- 2217585+Azuna1@users.noreply.github.com ✕ (has no Launchpad account)
```

**Comment by ktsakalozos** [comment]
@Azuna1 any updates on the CLA agreement? Thanks

**Comment by Azuna1** [comment]
I did not have a launchpad id and i have no idea what to enter in "Please add the Canonical Project Manager or contact" within the CLA formular.

**Comment by ktsakalozos** [comment]
> @ktsakalozos I did not have a launchpad id and i have no idea what to enter in "Please add the Canonical Project Manager or contact" within the CLA formular.

You can put "Alex Jones" in the Canonical Project Manager or contact, thank you.

**Comment by Azuna1** [comment]
Please rerun the checks now, ty

**Comment by ktsakalozos** [comment]
Thank you for this work @Azuna1

**Pull request merged**
