### PR TITLE
Add Shifu as a MicroK8s addon

### PR DESCRIPTION
**Pull request by saiyan86**
### Thank you for making MicroK8s better

Please reference the issue this PR is fixing, or provide a description of the problem addressed.

Usage:

`microk8s enable shifu`

Description:

This PR adds https://github.com/Edgenesis/shifu as a MicroK8s addon. Shifu is a Kubernetes-native IoT development framework. Shifu virtualizes your device into a K8s pod, and expose its capabilities as APIs. Through this, Shifu transforms the traditional complex IoT APP development into modern web APP development. 

Shifu's vision: Making developing an IoT solution as simple as developing a web APP!

*Also verify you have:*
* [x] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for this work @saiyan86 @FFFFFaraway could you please address the errors reported in the automated tests?

**Comment by saiyan86** [comment]
Sure! I'm on it.

**Comment by saiyan86** [comment]
@ktsakalozos could you pls authorize the tests again?

**Comment by ktsakalozos** [comment]
@saiyan86 @leepala  @FFFFFaraway nice work on getting the "Run tests" passing. Only a few lint fixes are needed (`black --check .` check) and the CLA singing. The CLA needs to be signed by all users having commits in this PR. The error we see is:
```
Checking the following users on Launchpad:
- 425499721@qq.com ✕ (has no Launchpad account)
- a964581583@hotmail.com ✕ (has no Launchpad account)
```
The users with the above emails should have a corresponding launchpad (https://launchpad.net/) account created with the same emails.

**Comment by tomqin93** [comment]
Hi @ktsakalozos , I have fixed formatting and CLA signing, please take a look

**Comment by tomqin93** [comment]
Huh, not sure why the cla-check failed again. I have created the account in launchpad and submitted the CLA form via the following link https://ubuntu.com/legal/contributors/agreement with email xqin@edgenesis.com

**Comment by ktsakalozos** [comment]
@tomqin93 I think it just took some time for CLA DB to be updated with your email. Its all green now, thank you.

**Comment by tomqin93** [comment]
@ktsakalozos Thanks! I think we are good on all checks

**Review by ktsakalozos — APPROVED** [review]
LGTM +1 thank you for this work!

**Comment by ktsakalozos** [comment]
Thank you for this work @saiyan86 @tomqin93 . The addon will be available with the 1.27 release.

Each addon gets its own place in the MicroK8s docs. Addons are linked from [1]. I prepared a page for Shifu in [2]. We can put there links to your work and what the next steps would be after enabling the addon.

Please let me know how would you like this docs page to look like.

[1] https://microk8s.io/docs/addons
[2] https://discuss.kubernetes.io/t/addon-shifu/23327

**Comment by tomqin93** [comment]
Hi @ktsakalozos , 
Thanks!
We would like to put a link to https://github.com/Edgenesis/shifu/ in the MicroK8s docs as the link to our work.

**Comment by ktsakalozos** [comment]
Hi @tomqin93 , this page will become part of our docs: https://discuss.kubernetes.io/t/addon-shifu/23327 

The v1.27 is not out yet so currently the MicroK8s docs do not have a link to shifu.

**Comment by tomqin93** [comment]
Hi @ktsakalozos , thank you for the update.
Can you please update the URL for the `the [Shifu official](https://shifu.run/) website` from https://shifu.run to https://shifu.dev ? Thanks!

**Pull request merged**
