### PR TITLE
Add microcks addon

### PR DESCRIPTION
**Pull request by yada**
Adding Microcks (CNCF Sandbox project) to Microk8s community addons.

Done:
* [x ] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [x ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for this PR @yada we will review it as soon as possible. In the mean time, could you please address the failing checks?

The error we get from the CLA check is:
```
Checking the following users on GitHub:
- yada ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])

Checking the following users on Launchpad:
- yada@users.noreply.github.com ✕ (has no Launchpad account)
```

**Comment by yada** [comment]
Thanks, @ktsakalozos I changed my GitHub settings to show my email when editing using the Web interface.
So CLA should pass now, tested using the CLI:
```
$ cla-check yacine@microcks.io
Logging into launchpad...
Querying participants...
✓  yacine@microcks.io (Yacine Kheddache) has signed the CLA
```

**Comment by ktsakalozos** [comment]
There is this error: `enable hook for microcks addon needs execute permissions`. Can you make sure the enable/disable hooks are executable?

**Comment by yada** [comment]
Ok got it, looks like the hook permissions have been reset when using the GitHub web interface to edit...
Should be ok now 🤞

**Comment by yada** [comment]
@ktsakalozos Can you launch the workflow again 🙏 
I have been able to run them successfully on my fork.

**Pull request merged**
