### PR TITLE
Update Microcks addon to version 1.8.0

### PR DESCRIPTION
**Pull request by yada**
…dynamically so the microcks community addon is always in sync.

### Thank you for making MicroK8s better

Please reference the issue this PR is fixing, or provide a description of the problem addressed.

*Also verify you have:*
* [ ] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [ ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

### CODE REVIEW

**Comment by yada** [comment]
Ready to merge with thanks 🙌

**Comment by ktsakalozos** [comment]
Hi @yada. Having an addon always use the latest version of the corresponding application imposes some challenges for both MicroK8s and the addon maintainer. If the project (MICROCKS in this case) wants to do a breaking change the MicroK8s builds will get blocked and the addon will be broken for the past releases.

Let me give you an example. Lets assume we accept this PR. Staring  from 1.29 the MICROCKS addon will always deploy the latest version. Lets assume that after 1.32 you decide to ship a version that is not compatible with 1.29 anymore. As soon as you do that the 1.29 release of MicroK8s will be broken and will stop building because the integration tests will fail.

Another reason we ship specific versions of addons and not the latest is because we want users to have a consistent UX. Lets say someone sets up a dev environment for all developers in his org. He does not want to have random components update without him knowing, right?

For this PR is would be best to switch the version to 1.8.0 instead of the latest. Thanks.

**Review by ktsakalozos — CHANGES_REQUESTED** [review]
Please do not deploy the latest version. Instead pin the version you would like to see released in the 1.29 k8s.

**Comment by yada** [comment]
Hi @ktsakalozos,
Thanks for the feedback. I'm not sure our addon may not introduce a breaking change, but I fully understand and agree with your point. I'll do a PR for each new version and pin Microcks release to Microk8s / k8S versions after QA on our side.
Regards,

**Comment by ktsakalozos** [comment]
Any update on this @yada ?

**Comment by yada** [comment]
Already updated, have you checked my commit?!

**Comment by ktsakalozos** [comment]
Ah I thought you wanted to do some QA. Sorry I missed that. Thank you for this work, it will be available with the 1.29 release.

**Comment by yada** [comment]
Thank you @ktsakalozos 🙌

**Pull request merged**
