### PR TITLE
chore: update argocd to version 4.5.0 and arm64 support

### PR DESCRIPTION
**Pull request by dirien**
### Thank you for making MicroK8s better

Please reference the issue this PR is fixing, or provide a description of the problem addressed.

*Also verify you have:*
* [x] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

This PR introduce following features:

- Update version of ArgoCD to 2.3.3
- Version can be set with -v flag
- arm64 support

Screenshots:

image
image
image
image
image

### CODE REVIEW

**Review by neoaggelos — COMMENTED** [review]
In arm64, I see that `argocd-applicationset-controller` gets into CrashLoopBackOff state (possibly because the image is not multi-arch?)

How should this be handled? Is there an option to disable the applicationset controller by default on arm64?

Please address this, and then we can merge in time for 1.24. Thanks @dirien !

**Comment by dirien** [comment]
Thanks for the feedback @neoaggelos. Do you have a arch detect helper function available? Otherwhise I will come up with a way to disable applicationset in the helm chart when on arm64 arch!

Or @neoaggelos, we remove the arm64 flag. as it looks like that ArgoCD is not fully arm64 compatible!

**Comment by neoaggelos** [comment]
I see 3 options:

1. Check `uname -m` against `x86_64` and act accordingly. I see https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L1880-L1882, so you can maybe use `--set applicationSet.enabled=false`
2. Disable arm64 arch altogether
3. Leave as is, with a note that applicationset controller is not yet compatible with arm64 (I expect that this should change soon).

From a maintainer point of view, I think is 2 is the easiest at the moment.

**Comment by dirien** [comment]
Thanks @neoaggelos for the feedback! I went with option two! As long ArgoCD is not full arm it makes sense to no give an arm option! 

I will keep an eye on this addon, as soon smth changes I will activate the arm option.

**Review by neoaggelos — APPROVED** [review]
Thanks @dirien

**Pull request merged**
