### PR TITLE
Disable ondat testing in containers because it is failing

### PR DESCRIPTION
**Pull request by ktsakalozos**
Tests on lxc containers are failing.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
@hubvu maybe you could offer some insight on this failure, is it expected?

Not much in the logs:
```
storageos     pod/storageos-scheduler-84b5f4cb5d-svv7k                0/1     CrashLoopBackOff   7 (3m25s ago)   15m
``` 

and
```
root@u1:~# microk8s.kubectl logs -n storageos     pod/storageos-node-qv4nz -c init
Error from server (BadRequest): container "init" in pod "storageos-node-qv4nz" is waiting to start: CreateContainerError
```

**Comment by hubvu** [comment]
@ktsakalozos if I understand this correctly, you are conducting tests to see if Ondat can run in LXC containers that are used for Kubernetes nodes? If so, I don't believe we have come across this use case yet of running Ondat on-top of nodes which are LXC containers..

**Comment by hubvu** [comment]
@ktsakalozos I deployed Ondat today through the community repo and I was able to reproduce this issue. I now don't believe it is because we cannot run under LXC containers but more likely due to the fact that in v1.26 KubeSchedulerConfiguration v1beta1 or v1beta2 are deprecated and removed in favour of v1beta3 - https://github.com/intel/platform-aware-scheduling/issues/104

This is likely why we didn't see this issue in v1.25 or below. This issue will be addressed in the next future release of Ondat and we point the scheduler to use the v1beta3 API instead.

**Comment by ktsakalozos** [comment]
Hi @hubvu is this addressed? Do we need to do anything with the addon?

**Comment by hubvu** [comment]
@ktsakalozos this is addressed and the fixes will be in the next upcoming release of Ondat which should be out soon - there is no need for us to do anything. When the new release is out, the add-on will point to the new version.

**Pull request merged**
