### PR TITLE
Adding the stunner add-on

### PR DESCRIPTION
**Pull request by smeng9**
### Thank you for making MicroK8s better

Add a new community add-on

*Also verify you have:*
* [x] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

### CODE REVIEW

**Review by eaudetcobello — COMMENTED** [review]
Thanks for your contribution. LGTM.

**Comment by smeng9** [comment]
Is there any additional changed needed? We could catch the MicroK8s 1.30 release cycle.

**Comment by eaudetcobello** [comment]
> Is there any additional changed needed? We could catch the MicroK8s 1.30 release cycle.

Hi smeng, I don't think more changes are needed. There is a failing test if you could look into it please? I re-ran the job in case it was a flake. Let's see.

**Comment by bschimke95** [comment]
Hello @smeng9,

It appears that the tests are still failing. You can view the details here: https://github.com/canonical/microk8s-community-addons/actions/runs/8578114130/job/23570692295?pr=223#step:4:290

Additionally, please ensure that you have signed the CLA (Contributor License Agreement). If you have already done so, verify that the name and email associated with your commits match the ones you used to sign the CLA.

Thanks!

**Comment by smeng9** [comment]
Hi @bschimke95 Can you help to rerun the tests? I have also fixed the cla.

**Comment by smeng9** [comment]
I have redone the cla signing with the users.noreply.github.com email address, fixed linter and skipped strict test.

We can run the GitHub actions again.

**Comment by bschimke95** [comment]
Please revert the skipping of strict tests. The tests was failing because of an outdated infra branch. That should now work again.

Also, there was a CLA bug that occasionally triggered false positives which was the reason for your CLA check to fail. This is fixed in https://github.com/canonical/microk8s-community-addons/pull/228.
Please rebase your branch on main to include that new check.

**Comment by smeng9** [comment]
Reverted and Rebased

**Comment by bschimke95** [comment]
Looks like there is still an issue with the CLA.
I'll investigate and get back to you.

**Review by bschimke95 — APPROVED** [review]
LGTM

**Pull request merged**
